language: node_js
node_js:
- node
deploy:
  - provider: npm
    email: "deven.phillips@gmail.com"
    api_key: "$API_TOKEN"
    on:
      tags: true
    tag: latest
    skip_cleanup: true
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    skip_cleanup: true
    file_glob: true
    file:
      - "reports/mutation/html/*"
      - "coverage/*"
      - "unit-test-reports/*"
    on:
      tags: true
addons:
  sonarcloud:
    organization: "infosec812-github" # the key of the org you chose at step #3
    token: "${SONAR_TOKEN}"
script:
  - npm run test
  - sonar-scanner
  - npm run stryker