language: node_js
node_js:
- node
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Deven Phillips"
  - git config --local user.email "deven.phillips@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(cat package.json | grep '\"version\"' | awk -F'"' '{print "v"$4}')}
  - git tag $TRAVIS_TAG
deploy:
  - provider: npm
    email: "deven.phillips@gmail.com"
    api_key: "$API_TOKEN"
    on:
      branch: master
    tag: latest
    skip_cleanup: true
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    skip_cleanup: true
    file_glob: true
    file:
      - "reports/mutation/html/*"
      - "coverage/*"
      - "unit-test-reports/*"
    on:
      branch: master
addons:
  sonarcloud:
    organization: "infosec812-github" # the key of the org you chose at step #3
    token: "${SONAR_TOKEN}"
script:
  - npm run test
  - sonar-scanner
  - npm run stryker