language: node_js
node_js:
- node
deploy:
  provider: npm
  email: deven.phillips@redhat.com
  api_key:
    secure: BSobR4bdZh5dmDMEEhPcguEJq3o6dQzu0WEUxknGEvDzpW8hzLgVWXsOc8py5O+1vdzsxIfrecVhGMSTPIZEa92TJkGutCiMsjLRM4FNsAPNnFkPn4pUNc/pHsYrfsvyGHmA8/d3ksXKuOBPXFJPrEcfpMfqdMPAL2zc61Scm4yszxc5kXEO13tUZlWl+LSZZ5TXA+LMC4hGMsLeNzbQZcqwNjxNvr2Fe8Md5FID0Q1xSsm9GopE1IzBKrooMechwqwA+VfDWHve3YxPMmOLwr1q6j+OF3PHz64GuY3eUqSztohZtSxOYt07bYgiMNceiwCtzRhmCta4Wzf+VRUinGc5ONgqP4GDev4rDp/o7XeWvdSgE3g6eR+P63cWg6vJuBxDw8o9572E/CVA3EjrbNhZeo48sTgkGbQ4P3bOZ3uKG4LiO1IR4fLwAjM8AYbc0YbJ/Xhg4r3+H62NNHMHdOtIvkISz7smBGKKvlwEx12gX3p4Vz6gbqVtZRW6k9GWdoiDwHlszXD4WMZaIvKQt20e3IYbBw97amLwQ4j1El16u05fk271peqe+TcZzK77s4qM0LCAR1wPJ7EpAMnWxq28DwVUwviWbUAjhSuBc8WZFhLIOGtxGHaiR3cvBdCb0+gIZVStKEPk4GPUj2OamSLQllxZfRU8FgyujWPLmYw=
  on:
    branch: master
  tag: next
